name: wardly_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7 # â† UPDATE INI (versi terbaru)
  path_provider: ^2.0.11
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
